drop table User if exists;

create table User (
  id bigint generated by default as identity,
  cardId varchar(255),
  name varchar(255),
  primary key (id)
);

INSERT INTO USER (cardId, name) VALUES ('332522198501206956','周某某');
INSERT INTO USER (cardId, name) VALUES ('332522198612206950','赵某某');